// Sample product data for the website - RIDGID Products
export interface Product {
    id: string;
    name: string;
    subtitle: string;
    price: number;
    originalPrice?: number;
    image: string;
    badge?: "NEW" | "REFURB" | "RESTOCKED";
    rating: number;
    reviewCount: number;
    category: "new" | "refurbished";
    type: string;
    sku?: string;
    modelNumber?: string;
}

export const featuredProducts: Product[] = [
    {
        id: "ridgid-rp-351",
        name: "RIDGID RP 351",
        subtitle: "Press Tool - Compact & Powerful",
        price: 2499.0,
        image: "https://cdn2.ridgid.com/resources/images/3b1f0c2f-7300-417f-a0de-a2ea0da34c61",
        badge: "NEW",
        rating: 4.9,
        reviewCount: 156,
        category: "new",
        type: "Press Tools",
        sku: "67223",
    },
    {
        id: "ridgid-rp-350",
        name: "RIDGID RP 350",
        subtitle: "Standard Pressing Tool",
        price: 1899.0,
        originalPrice: 2299.0,
        image: "https://cdn2.ridgid.com/resources/images/cded2670-a792-4a56-a129-e5fc7fbece62",
        badge: "REFURB",
        rating: 4.7,
        reviewCount: 89,
        category: "refurbished",
        type: "Press Tools",
        modelNumber: "RP 350",
    },
    {
        id: "ridgid-k40b-drain-machine",
        name: "RIDGID K40B Drain Machine",
        subtitle: "Battery Powered Drain Cleaning",
        price: 899.0,
        image: "https://cdn2.ridgid.com/resources/images/bbad6855-e409-4b92-97b6-572be81cd048",
        badge: "NEW",
        rating: 5.0,
        reviewCount: 234,
        category: "new",
        type: "Drain Cleaning",
    },
    {
        id: "ridgid-600-series-bender",
        name: "RIDGID 600 Series Bender",
        subtitle: "Precision Tube Bending",
        price: 349.0,
        originalPrice: 449.0,
        image: "https://cdn2.ridgid.com/resources/images/326e15bb-1d10-4fdb-a498-873ae1ffd25c",
        badge: "REFURB",
        rating: 4.9,
        reviewCount: 67,
        category: "refurbished",
        type: "Benders",
    },
];

export const newEquipmentProducts: Product[] = [
    {
        id: "ridgid-rp-351-new",
        name: "RIDGID RP 351 Press Tool",
        subtitle: "Compact design, inline pressing for tight spaces with 360° rotation.",
        price: 2499.0,
        image: "https://cdn2.ridgid.com/resources/images/3b1f0c2f-7300-417f-a0de-a2ea0da34c61",
        badge: "NEW",
        rating: 4.9,
        reviewCount: 142,
        category: "new",
        type: "Press Tools",
        sku: "67223",
    },
    {
        id: "ridgid-k40pfg-sink-machine",
        name: "RIDGID K40PFG Sink Machine",
        subtitle: "Powered feed, autofeed technology for drain cleaning.",
        price: 599.99,
        image: "https://cdn2.ridgid.com/resources/images/d1ec3764-1adf-4d1f-b4d6-9b08e82ebdcf",
        badge: "NEW",
        rating: 5.0,
        reviewCount: 89,
        category: "new",
        type: "Drain Cleaning",
    },
    {
        id: "ridgid-40a-tristand",
        name: "RIDGID 40A Portable Tristand",
        subtitle: "Portable chain vise stand for 1/8\" to 2-1/2\" pipe.",
        price: 329.50,
        image: "https://cdn2.ridgid.com/resources/images/326f2b05-4015-4977-8661-6c52aa841013",
        badge: "RESTOCKED",
        rating: 4.8,
        reviewCount: 156,
        category: "new",
        type: "Stands & Vises",
    },
    {
        id: "ridgid-chain-tongs",
        name: "RIDGID Chain Tongs",
        subtitle: "Heavy-duty chain tongs for large pipe work.",
        price: 189.0,
        image: "https://cdn2.ridgid.com/resources/images/9fd30644-e81b-4417-a755-140b9cfe4cf8",
        rating: 4.9,
        reviewCount: 203,
        category: "new",
        type: "Wrenches",
        sku: "92665",
    },
    {
        id: "ridgid-aluminum-end-wrench",
        name: "RIDGID Aluminum End Wrench",
        subtitle: "Lightweight aluminum construction for reduced fatigue.",
        price: 79.0,
        image: "https://cdn2.ridgid.com/resources/images/5f274a16-98f1-457f-8c2e-7094652d38a7",
        badge: "NEW",
        rating: 4.7,
        reviewCount: 134,
        category: "new",
        type: "Wrenches",
        sku: "90117",
    },
    {
        id: "ridgid-strap-wrench",
        name: "RIDGID 17\" Strap Wrench",
        subtitle: "For 3.5\" (90mm) pipes. Non-marring, secure grip.",
        price: 49.0,
        image: "https://cdn2.ridgid.com/resources/images/274d042c-11af-4360-ae57-8922253c62ec",
        badge: "NEW",
        rating: 5.0,
        reviewCount: 312,
        category: "new",
        type: "Wrenches",
        sku: "31335",
    },
    {
        id: "ridgid-rhp700lr",
        name: "RIDGID RHP700LR Press Tool",
        subtitle: "Hydraulic pressing tool for large diameter applications.",
        price: 3299.0,
        image: "https://cdn2.ridgid.com/resources/images/650b4786-571f-4b56-9e7a-623caadf00df",
        badge: "NEW",
        rating: 4.9,
        reviewCount: 78,
        category: "new",
        type: "Press Tools",
        modelNumber: "RHP700LR",
    },
    {
        id: "ridgid-flexshaft-k9-306",
        name: "RIDGID FlexShaft K9-306",
        subtitle: "Penetrating tip head for drain cleaning.",
        price: 129.0,
        image: "https://cdn2.ridgid.com/resources/images/b16be8e6-52f8-4c51-9ac4-8cb4ad519fc6",
        rating: 4.8,
        reviewCount: 56,
        category: "new",
        type: "Drain Cleaning",
        sku: "71858",
    },
];

export const refurbishedProducts: Product[] = [
    {
        id: "ridgid-rp-350-ref",
        name: "RIDGID RP 350 Press Tool",
        subtitle: "Grade A Condition - Certified Refurbished",
        price: 1599.0,
        originalPrice: 2299.0,
        image: "https://cdn2.ridgid.com/resources/images/cded2670-a792-4a56-a129-e5fc7fbece62",
        badge: "REFURB",
        rating: 4.7,
        reviewCount: 42,
        category: "refurbished",
        type: "Press Tools",
        modelNumber: "RP 350",
    },
    {
        id: "ridgid-600-bender-ref",
        name: "RIDGID 600 Series Tube Bender",
        subtitle: "Grade A Condition - Factory Certified",
        price: 279.0,
        originalPrice: 449.0,
        image: "https://cdn2.ridgid.com/resources/images/326e15bb-1d10-4fdb-a498-873ae1ffd25c",
        badge: "REFURB",
        rating: 5.0,
        reviewCount: 128,
        category: "refurbished",
        type: "Benders",
    },
    {
        id: "ridgid-k40b-ref",
        name: "RIDGID K40B Drain Machine",
        subtitle: "Grade A Condition - Battery Included",
        price: 649.0,
        originalPrice: 899.0,
        image: "https://cdn2.ridgid.com/resources/images/bbad6855-e409-4b92-97b6-572be81cd048",
        badge: "REFURB",
        rating: 4.8,
        reviewCount: 98,
        category: "refurbished",
        type: "Drain Cleaning",
    },
    {
        id: "ridgid-stainless-tools-ref",
        name: "RIDGID Stainless Steel Tool Set",
        subtitle: "Grade A Condition - Complete Set",
        price: 399.0,
        originalPrice: 599.0,
        image: "https://cdn2.ridgid.com/resources/images/bff062fa-7c13-4f6d-8381-9ed63c7d6942",
        badge: "REFURB",
        rating: 4.9,
        reviewCount: 56,
        category: "refurbished",
        type: "Tool Sets",
    },
    {
        id: "ridgid-roll-dies-ref",
        name: "RIDGID Roll Dies Set",
        subtitle: "Grade B Condition - Great Value",
        price: 199.0,
        originalPrice: 349.0,
        image: "https://cdn2.ridgid.com/resources/images/2dfb23df-9bc3-46c5-9ff0-59cce9576916",
        badge: "REFURB",
        rating: 4.5,
        reviewCount: 23,
        category: "refurbished",
        type: "Dies",
    },
    {
        id: "ridgid-tristand-ref",
        name: "RIDGID 40A Portable Tristand",
        subtitle: "Grade B Condition - Fully Functional",
        price: 229.0,
        originalPrice: 329.0,
        image: "https://cdn2.ridgid.com/resources/images/326f2b05-4015-4977-8661-6c52aa841013",
        badge: "REFURB",
        rating: 4.6,
        reviewCount: 89,
        category: "refurbished",
        type: "Stands & Vises",
    },
    {
        id: "ridgid-918-roll-groover",
        name: "RIDGID 918 Hydraulic Roll Groover",
        subtitle: "Pre-Owned - Excellent Condition",
        price: 1999.99,
        originalPrice: 2899.00,
        image: "/images/products/ridgid-918.webp",
        badge: "REFURB",
        rating: 4.8,
        reviewCount: 15,
        category: "refurbished",
        type: "Press Tools",
        sku: "918-ROLL-GROOVER",
    },
    {
        id: "ridgid-916-manual-groover",
        name: "RIDGID 916 Manual Roll Groover",
        subtitle: "Refurbished - 1-1/4\" to 6\" Pipe",
        price: 799.99,
        originalPrice: 1099.00,
        image: "/images/products/ridgid-916.webp",
        badge: "REFURB",
        rating: 4.7,
        reviewCount: 22,
        category: "refurbished",
        type: "Press Tools",
        sku: "916-MANUAL-GROOVER",
    },
    {
        id: "ridgid-40a-yoke-vise",
        name: "RIDGID 40A Portable Yoke Vise",
        subtitle: "Refurbished - Heavy Duty 1/8\"-2-1/2\"",
        price: 1175.00,
        originalPrice: 1550.00,
        image: "/images/products/ridgid-40a.webp",
        badge: "REFURB",
        rating: 4.9,
        reviewCount: 34,
        category: "refurbished",
        type: "Stands & Vises",
        sku: "40130-REF",
    },
    {
        id: "husky-7027302-control-board",
        name: "Husky Altanium Temperature Control Board",
        subtitle: "New Open Box - Dual Channel 16A",
        price: 199.99,
        originalPrice: 299.99,
        image: "/images/products/husky-control-board.webp",
        badge: "RESTOCKED",
        rating: 5.0,
        reviewCount: 3,
        category: "refurbished",
        type: "Accessories",
        sku: "7027302",
    },
    {
        id: "asco-redhat-8210g002",
        name: "ASCO RedHat Solenoid Valve",
        subtitle: "New Open Box - 24/60 Solenoid",
        price: 129.99,
        originalPrice: 189.99,
        image: "/images/products/asco-solenoid.webp",
        badge: "RESTOCKED",
        rating: 4.8,
        reviewCount: 8,
        category: "refurbished",
        type: "Accessories",
        sku: "8210G002",
    },
    {
        id: "ridgid-thread-cutting-oil",
        name: "RIDGID Endura-Clear Thread Cutting Oil",
        subtitle: "1 Gallon - Factory Sealed",
        price: 34.0,
        originalPrice: 49.0,
        image: "https://cdn2.ridgid.com/resources/images/997d00d1-4da5-49b0-ba84-280b2feed004",
        badge: "RESTOCKED",
        rating: 5.0,
        reviewCount: 234,
        category: "new",
        type: "Accessories",
        sku: "32808",
    },
    {
        id: "ridgid-dark-thread-oil",
        name: "RIDGID Dark Thread Cutting Oil",
        subtitle: "5 Gallon Bucket",
        price: 89.0,
        originalPrice: 129.0,
        image: "https://cdn2.ridgid.com/resources/images/010064df-3236-46ef-a8ee-477ef00bab61",
        badge: "RESTOCKED",
        rating: 4.9,
        reviewCount: 167,
        category: "new",
        type: "Accessories",
        sku: "41600",
    },
];
